return {
	temperate = { id = "temperate", displayName = "Temperate", supplyLimitMod = 0, attritionMod = 0 },
	mediterranean = { id = "mediterranean", displayName = "Mediterranean", supplyLimitMod = 0, attritionMod = 0 },
	continental = { id = "continental", displayName = "Continental", supplyLimitMod = -1, attritionMod = 0.05 },
	subarctic = { id = "subarctic", displayName = "Subarctic", supplyLimitMod = -2, attritionMod = 0.15 },
	arctic = { id = "arctic", displayName = "Arctic", supplyLimitMod = -3, attritionMod = 0.25 },
	arid = { id = "arid", displayName = "Arid", supplyLimitMod = -1, attritionMod = 0.1 },
	subtropical = { id = "subtropical", displayName = "Subtropical", supplyLimitMod = 0, attritionMod = 0.05 },
	tropical = { id = "tropical", displayName = "Tropical", supplyLimitMod = -1, attritionMod = 0.15 },
	monsoon = { id = "monsoon", displayName = "Monsoon", supplyLimitMod = -1, attritionMod = 0.1 },
}
