return {
	absolutism = {
		id = "absolutism",
		displayName = "Absolutism",
		modifiers = {
			base_stability = 0.12,
			unrest_reduction = -0.20,
			tax_income = -0.10,
			military_upkeep = -0.30,
			justification_time = -0.30,
		},
	},
	enlightened_absolutism = {
		id = "enlightened_absolutism",
		displayName = "Enlightened Absolutism",
		modifiers = {
			unrest_reduction = 0.25,
			offensive_stability_hit = -0.01,
			tax_income = 0.25,
			investment_cost = -0.20,
			military_upkeep = 0.05,
			justification_time = 0.30,
		},
	},
	liberalism = {
		id = "liberalism",
		displayName = "Liberalism",
		modifiers = {
			unrest_reduction = 0.25,
			offensive_stability_hit = -0.02,
			tax_income = 0.40,
			investment_cost = -0.20,
			military_upkeep = 0.05,
			justification_time = 0.50,
		},
	},
	republicanism = {
		id = "republicanism",
		displayName = "Republicanism",
		modifiers = {
			base_stability = 0.05,
			manpower_increase = 0.10,
			tax_income = 0.10,
			military_upkeep = -0.10,
			justification_time = 0.0,
		},
	},
	conservatism = {
		id = "conservatism",
		displayName = "Conservatism",
		modifiers = {
			base_stability = 0.02,
			unrest_reduction = -0.15,
			research_output = -0.15,
			tax_income = 0.10,
			manpower_increase = 0.10,
			justification_time = -0.40,
		},
	},
	tribalism = {
		id = "tribalism",
		displayName = "Tribalism",
		modifiers = {
			base_stability = -0.10,
			unrest_reduction = 0.10,
			tax_income = -0.25,
			manpower_increase = 0.25,
			military_upkeep = -0.30,
			research_output = -0.20,
			justification_time = -0.30,
		},
	},
}
