return {
	europe = { id = "europe", displayName = "Europe" },
	near_east = { id = "near_east", displayName = "Near East" },
	central_asia = { id = "central_asia", displayName = "Central Asia" },
	east_asia = { id = "east_asia", displayName = "East Asia" },
	south_asia = { id = "south_asia", displayName = "South Asia" },
	southeast_asia = { id = "southeast_asia", displayName = "Southeast Asia" },
	americas_north = { id = "americas_north", displayName = "North America" },
	americas_south = { id = "americas_south", displayName = "South America" },
	africa_north = { id = "africa_north", displayName = "North Africa" },
	africa_sub = { id = "africa_sub", displayName = "Sub-Saharan Africa" },
	oceania = { id = "oceania", displayName = "Oceania" },
}
